# Generated by Django 5.0.2 on 2024-04-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.TextField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
